steps:
# First Clone from GitHub Repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Ankit-Deswal/GCPBuild.git']
  dir: '/workspace'

# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag'
    - 'gcr.io/logical-light-411605/gcpbuild.git'
    - '.'
  dir: '/workspace/GCPBuild'

# Push the image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/logical-light-411605/gcpbuild.git'
    
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Setting Kubernetes cluster configuration..."
      export CLOUDSDK_COMPUTE_REGION=us-central1
      export CLOUDSDK_COMPUTE_ZONE=us-central1-a
      export CLOUDSDK_CONTAINER_CLUSTER=ankitdeswal-cluster-1

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'deployment.yaml'
  
