steps:
# First Clone from GitHub Repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Ankit-Deswal/GCPBuild.git']
  dir: '/workspace'

# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag'
    - 'gcr.io/logical-light-411605/gcpbuild:$(date +%s)'
    - '.'
  dir: '/workspace/GCPBuild'
  
# Create Volume for Database
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'volume'
    - 'create'
    - 'database-volume'

# Create Volume for Logs
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'volume'
    - 'create'
    - 'logs-volume'

# Push the image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/logical-light-411605/gcpbuild:$(date +%s)'
    

  
